openapi: 3.0.0
info:
  version: 1.0.0
  title: Bitganj
servers:
  - url: 'http://localhost:3000'
paths:
  /Info:
    get:
      summary: 'Informational endpoint: Returns details about some public info'
      operationId: getSessionState
      tags:
        - session
      parameters:
        - name: action
          in: query
          description: what kind of info
          required: true
          schema:
            type: string
            format: string
      responses:
        '200':
          description: 'Sample response: Details about a user by ID'
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Session:
      type: object
      required:
        - id
        - ip
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string